name: Periodic Check

on: workflow_dispatch

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check deployed url
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://throbbing-voice-8584.fly.dev/health
